apiVersion: apps/v1
kind: Deployment
metadata:
  name: exh-agent-controller
  namespace: exh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: exh-agent-controller
  template:
    metadata:
      labels:
        run: exh-agent-controller
    spec:
      serviceAccountName: octolamp-service-account
      containers:
      - env:
        - name: AZDO_ORG_URI
          value: https://dev.azure.com/juliuskevinezz
        - name: AZDO_TOKEN
          value: "wofaculflpgrhglj5cgfwuryx57yzw2ctjmyvvx2gfqdsiwgjkpa"
        - name: AZDO_POOLNAME
          value: "agentpool"
        - name: TARGET_NAMESPACE
          value: "azdo-agents"
        - name: STANDBY_AGENT_COUNT
          value: "2"
        - name: MAX_AGENT_COUNT
          value: "25"                             
        image: moimhossain/octolamp-agent-controller:v1.0.0-beta
        imagePullPolicy: Always
        name: exh-agent-controller
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
